name = "grief-matters-cms"
main = "./worker/index.ts"
compatibility_date = "2024-09-08"
preview_urls = false

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
API_BASE_URL = "https://cms.whygriefmatters.org"

[env.dev]
vars = { API_BASE_URL = "http://localhost:8787" }

[env.production]
vars = { API_BASE_URL = "https://cms.whygriefmatters.org" }
