name = "grief-matters-cms"
main = "./worker/index.ts"
compatibility_date = "2024-09-08"
preview_urls = false

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[kv_namespaces]]
binding = "WGM_BROKEN_LINKS"
id = "88f9bbb672784739badd2e5bc1ab9c91"

[triggers]
crons = ["0 3 * * 0"]

[vars]
API_BASE_URL = "https://cms.whygriefmatters.org"

[env.dev]
vars = { API_BASE_URL = "http://localhost:8787" }

[env.production]
vars = { API_BASE_URL = "https://cms.whygriefmatters.org" }
